import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/header";
import ReactQueryProvider from "@/providers/react-query-provider";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} min-h-screen h-full antialiased tracking-wider`}
    >
      <body className="h-screen flex flex-col tracking-wider">
        {/* <div>Nav bar</div> */}
        <ReactQueryProvider>
           {children}
        </ReactQueryProvider>
       
        <Toaster/>
      </body>
    </html>
  );
}